apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    app: mosquitto-broker
  ports:
    - protocol: TCP
      name: mqtt-8001
      port: 8001
      targetPort: 8001
      nodePort: 8001
  type: LoadBalancer
  externalIPs:
  - 192.186.0.1
