apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: mosquitto-broker
  name: mosquitto-broker
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mosquitto-broker
  template:
    metadata:
      labels: 
        app: mosquitto-broker
    spec:
      containers:
      - image: eclipse-mosquitto:latest
        name: mosquitto-broker-8001
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: conf-8001
          mountPath: /mosquitto/config/mosquitto.conf
      volumes:
      - name: conf-8001
        hostPath:
          path: /home/boortmans/Nextcloud/flint/flint/broker/mosquitto/mosquitto-8001.conf
