apiVersion: apps/v1
kind: Deployment
metadata:
  name: lora-adapter
  labels:
    app: lora-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lora-adapter
  template:
    metadata:
      labels:
        app: lora-adapter
    spec:
      containers:
      - name: sink
        image: gitlab.ilabt.imec.be:4567/bamoons/vno:sink
        imagePullPolicy: Always
        env:
          - name: config
            value: "sink/conf/adapter_conf.ini"
          - name: loglevel
            value: "DEBUG"
        volumeMounts:
          - name: conf-lora
            mountPath: /usr/src/app/sink/conf
          - name: sock
            mountPath: /sock
      - name: lora-adapter
        image: gitlab.ilabt.imec.be:4567/bamoons/vno:lora-adapter
        imagePullPolicy: Always
        env:
          - name: config
            value: "lora/conf/adapter_conf.ini"
          - name: loglevel
            value: "DEBUG"
        volumeMounts:
          - name: conf-lora
            mountPath: /usr/src/app/lora/conf
          - name: sock
            mountPath: /sock
      imagePullSecrets:
      - name: vno
      volumes:
      - name: conf-lora
        hostPath:
          path: /users/bart/vno/adapters/agents/lora/conf/
      - name: sock
        emptyDir: {}
